name: Glados

on:
    push:

env:
    MIRROR_URL: "git@github.com:EpitechPromo2026/B-FUN-500-PAR-5-2-glados-evan.labourdette.git"

jobs:
    push_to_mirror:
        name: Mirorring
        runs-on: ubuntu-latest
        steps:
          - name: Check repository
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
          - name: Check mirorring
            uses: pixta-dev/repository-mirroring-action@v1
            with:
                target_repo_url:
                    ${{ env.MIRROR_URL }}
                ssh_private_key:
                    ${{ secrets.GIT_SSH_PRIVATE_KEY }}