name: Functional tests

on: [push, pull_request]

jobs:
  functional-tests:
    runs-on: ubuntu-20.04
    container:
      image: haskell:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"

      - name: Build project
        run: |
          stack build --install-ghc --allow-different-user
          stack --local-bin-path build install
          mv build/glados-exe glados