name: Build and Mirror

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.10.3
          cabal-version: 3.4.0.0
          stack-version: 2.7.3

      - name: Build project
        run: |
          stack build --install-ghc --allow-different-user
          stack --local-bin-path build install
          mv build/glados-exe glados

  mirror:
    name: Mirorring
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Check mirorring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
            target_repo_url:
                ${{ env.MIRROR_URL }}
            ssh_private_key:
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}